# Generated by Django 5.0.3 on 2024-05-02 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_customuser_age_alter_customuser_height_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='user',
        ),
        migrations.RemoveField(
            model_name='meal',
            name='user',
        ),
    ]
